# Generated by Django 4.0.2 on 2022-05-02 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poetica', '0006_alter_poem_options_poem_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(max_length=256)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poem_comments', to='poetica.poem')),
            ],
        ),
    ]
