# Generated by Django 4.0.2 on 2022-05-03 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetica', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='likes',
            field=models.ManyToManyField(related_name='poems_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
