# Generated by Django 4.0.2 on 2022-05-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetica', '0009_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
