# Generated by Django 4.0.2 on 2022-05-09 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poetica', '0012_user_bio_body_delete_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio_body',
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_body', models.TextField(max_length=256)),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_bio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
